function jry_wb_nd_fresh(qiangzhi)
{
	jry_nd_load_count=2;
	jry_wb_indexeddb_get_lasttime('nd_group',function(time)
	{	
		if(jry_wb_compare_time(time,jry_nd_fast_save_message.group)<0||qiangzhi)
			jry_wb_sync_data_with_server('nd_group',jry_wb_message.jry_wb_host+'jry_wb_netdisk/jry_nd_get_information.php?action=group',null,function(data)
			{
				jry_nd_group=data;
				jry_nd_load_count--;
				if(jry_nd_load_count==0)
					jry_wb_nd_show_files_by_dir(decodeURI(document.location.hash)!=''?decodeURI(document.location.hash).split('#')[1]:'/');
				return jry_nd_fast_save_message.group;
			});
		else
			jry_wb_indexeddb_get_all('nd_group',(data)=>
			{
				jry_nd_group=data;
				jry_nd_load_count--;
				if(jry_nd_load_count==0)
					jry_wb_nd_show_files_by_dir(decodeURI(document.location.hash)!=''?decodeURI(document.location.hash).split('#')[1]:'/');			
			});
	});
	jry_wb_indexeddb_get_lasttime('nd_area',function(time)
	{		
		if(jry_wb_compare_time(time,jry_nd_fast_save_message.area)<0||qiangzhi)
			jry_wb_sync_data_with_server('nd_area',jry_wb_message.jry_wb_host+'jry_wb_netdisk/jry_nd_get_information.php?action=area',null,function(data)
			{
				jry_nd_area=data;
				jry_nd_load_count--;
				if(jry_nd_load_count==0)
					jry_wb_nd_show_files_by_dir(decodeURI(document.location.hash)!=''?decodeURI(document.location.hash).split('#')[1]:'/');
				return jry_nd_fast_save_message.area;
			});
		else
			jry_wb_indexeddb_get_all('nd_area',(data)=>
			{
				jry_nd_area=data;
				jry_nd_load_count--;
				if(jry_nd_load_count==0)
					jry_wb_nd_show_files_by_dir(decodeURI(document.location.hash)!=''?decodeURI(document.location.hash).split('#')[1]:'/');			
			});	
	});
	if(!jry_nd_share_mode_flag)
		jry_wb_nd_fresh_file_list(qiangzhi,function(){if(jry_nd_load_count==0)jry_wb_nd_show_files_by_dir(decodeURI(document.location.hash)!=''?decodeURI(document.location.hash).split('#')[1]:'/');});
	if(!jry_nd_share_mode_flag)
		jry_wb_nd_fresh_share_list(qiangzhi,function(){if(jry_nd_load_count==0)jry_wb_nd_show_files_by_dir(decodeURI(document.location.hash)!=''?decodeURI(document.location.hash).split('#')[1]:'/');});	
}