<?php
	include_once("../jry_wb_tools/jry_wb_includes.php");
	include_once("../jry_wb_configs/jry_wb_config_netdisk.php");
	include_once("jry_wb_nd_tools.php");	
	include_once("jry_nd_file_type.php");
	include_once("jry_nd_aly_includes.php");
	include_once("jry_nd_database_include.php");
	include_once("jry_nd_direct_include.php");
	include_once("jry_wb_local_include.php");
?>