<?php
	include_once('jry_wb_config_default_system.php');
	$JRY_WB_TP_QQ_OAUTH_CONFIG=(object)array(
		'appid'=>'',
		'appkey'=>'',
		'callback'=>JRY_WB_HOST.'jry_wb_tp_callback/tencent.php',
		'scope'=>'get_user_info',
		'errorReport'=>true,
		'storageType'=>'file',
		'host'=>'localhost',
		'user'=>'root',
		'password'=>'root',
		'database'=>'test'
	);
?>