<?php
	define('JRY_WB_DATABASE_GENERAL_PREFIX'				,JRY_WB_DATABASE_ALL_PREFIX	.'general_'		);
	define('JRY_WB_DATABASE_MAINPAGE_PREFIX'			,JRY_WB_DATABASE_ALL_PREFIX	.'mainpage_'	);
	define('JRY_WB_DATABASE_MANAGE_SYSTEM_PREFIX'		,JRY_WB_DATABASE_ALL_PREFIX	.'manage_'		);
	define('JRY_WB_DATABASE_SMALL_APPLICATION_PREFIX'	,JRY_WB_DATABASE_ALL_PREFIX	.'smallapp_'	);
	define('JRY_WB_DATABASE_NETDISK_PREFIX'				,JRY_WB_DATABASE_ALL_PREFIX	.'netdisk_'		);
	define('JRY_WB_DATABASE_LOG_PREFIX'					,JRY_WB_DATABASE_ALL_PREFIX	.'log_'			);
	define('JRY_WB_DATABASE_CHAT_PREFIX'				,JRY_WB_DATABASE_ALL_PREFIX	.'chat_'		);
	define('JRY_WB_DATABASE_ONLINE_JUDGE_PREFIX'		,JRY_WB_DATABASE_ALL_PREFIX	.'online_judge_');
	define('JRY_WB_DATABASE_SCHOOL_PREFIX'				,JRY_WB_DATABASE_ALL_PREFIX	.'school_'		);
	define('JRY_WB_DATABASE_BLOG_PREFIX'				,JRY_WB_DATABASE_ALL_PREFIX .'blog_'		);
	define('JRY_WB_DATABASE_SPIDERS_PREFIX'				,JRY_WB_DATABASE_ALL_PREFIX .'spider_'		);
	define('JRY_WB_DATABASE_GENERAL'					,JRY_WB_DATABASE_NAME	.'.'.JRY_WB_DATABASE_GENERAL_PREFIX				);
	define('JRY_WB_DATABASE_MAINPAGE'					,JRY_WB_DATABASE_NAME	.'.'.JRY_WB_DATABASE_MAINPAGE_PREFIX			);
	define('JRY_WB_DATABASE_MANAGE_SYSTEM'				,JRY_WB_DATABASE_NAME	.'.'.JRY_WB_DATABASE_MANAGE_SYSTEM_PREFIX		);
	define('JRY_WB_DATABASE_SMALL_APPLICATION'			,JRY_WB_DATABASE_NAME	.'.'.JRY_WB_DATABASE_SMALL_APPLICATION_PREFIX	);
	define('JRY_WB_DATABASE_NETDISK'					,JRY_WB_DATABASE_NAME	.'.'.JRY_WB_DATABASE_NETDISK_PREFIX				);	
	define('JRY_WB_DATABASE_LOG'						,JRY_WB_DATABASE_NAME	.'.'.JRY_WB_DATABASE_LOG_PREFIX					);
	define('JRY_WB_DATABASE_CHAT'						,JRY_WB_DATABASE_NAME	.'.'.JRY_WB_DATABASE_CHAT_PREFIX				);			
	define('JRY_WB_DATABASE_ONLINE_JUDGE'				,JRY_WB_DATABASE_NAME	.'.'.JRY_WB_DATABASE_ONLINE_JUDGE_PREFIX		);
	define('JRY_WB_DATABASE_SCHOOL'						,JRY_WB_DATABASE_NAME	.'.'.JRY_WB_DATABASE_SCHOOL_PREFIX				);
	define('JRY_WB_DATABASE_BLOG'						,JRY_WB_DATABASE_NAME	.'.'.JRY_WB_DATABASE_BLOG_PREFIX				);	
	define('JRY_WB_DATABASE_SPIDERS'					,JRY_WB_DATABASE_NAME	.'.'.JRY_WB_DATABASE_SPIDERS_PREFIX				);
	
	
	
	
	if(!JRY_WB_HOST_SWITCH)
	{
		define('jry_wb_host_database_general_prefix'		,JRY_WB_HOST_DATABASE_ALL_PREFIX.'general_');
		define('jry_wb_host_database_general'				,JRY_WB_HOST_DATABASE_NAME		.'.'.JRY_WB_DATABASE_GENERAL_PREFIX);		
	}
?>