<?php
	define('jry_wb_database_general_prefix',constant('jry_wb_database_all_prefix').'general_');
	define('jry_wb_database_general',constant('jry_wb_database_name').'.'.constant('jry_wb_database_general_prefix'));
	define("jry_wb_database_mainpage_prefix",constant('jry_wb_database_all_prefix').'mainpage_');
	define('jry_wb_database_mainpage',constant('jry_wb_database_name').'.'.constant('jry_wb_database_mainpage_prefix'));
	define('jry_wb_database_manage_system_prefix',constant('jry_wb_database_all_prefix').'manage_');
	define('jry_wb_database_manage_system',constant('jry_wb_database_name').'.'.constant('jry_wb_database_manage_system_prefix'));
	define('jry_wb_database_small_app_prefix',constant('jry_wb_database_all_prefix').'smallapp_');
	define('jry_wb_database_small_app',constant('jry_wb_database_name').'.'.constant('jry_wb_database_small_app_prefix'));
	define('jry_wb_database_game_prefix',constant('jry_wb_database_all_prefix').'game_');
	define('jry_wb_database_game',constant('jry_wb_database_name').'.'.constant('jry_wb_database_game_prefix'));
	define('competitionpro',constant('jry_wb_database_all_prefix').'competition_');
	define('competitiondb',constant('jry_wb_database_name').'.'.constant('competitionpro'));
	define('ojpro',constant('jry_wb_database_all_prefix').'oj_');
	define('ojdb',constant('jry_wb_database_name').'.'.constant('ojpro'));
	define('blogpro',constant('jry_wb_database_all_prefix').'blog_');
	define('blogdb',constant('jry_wb_database_name').'.'.constant('blogpro'));	
	define('jry_wb_school_prefix',constant('jry_wb_database_all_prefix').'school_');
	define('jry_wb_school',constant('jry_wb_database_name').'.'.constant('jry_wb_school_prefix'));
	define('picturebedpro',constant('jry_wb_database_all_prefix').'picturebed_');
	define('picturebeddb',constant('jry_wb_database_name').'.'.constant('picturebedpro'));	
	define('spiderpro',constant('jry_wb_database_all_prefix').'spider_');
	define('spiderdb',constant('jry_wb_database_name').'.'.constant('spiderpro'));
	define('jry_wb_netdisk_prefix',constant('jry_wb_database_all_prefix').'netdisk_');
	define('jry_wb_netdisk',constant('jry_wb_database_name').'.'.constant('jry_wb_netdisk_prefix'));	
	define('jry_wb_database_log_prefix',constant('jry_wb_database_all_prefix').'log_');
	define('jry_wb_database_log',constant('jry_wb_database_name').'.'.constant('jry_wb_database_log_prefix'));		
	if(!constant('jry_wb_host_switch'))
	{
		define('jry_wb_host_database_general_prefix',constant('jry_wb_host_database_all_prefix').'general_');
		define('jry_wb_host_database_general',constant('jry_wb_host_database_name').'.'.constant('jry_wb_database_general_prefix'));		
	}
?>