<?php
	include_once("../tools/jry_wb_includes.php");
	$conn=jry_wb_connect_database();
	$admin_mode=(($_GET['admin_mode']=='true')&&($jry_wb_login_user['id']!=-1)&&$jry_wb_login_user['compentence']['manageusers']&&$jry_wb_login_user['compentence']['manage']);	
	$user=jry_wb_get_user($conn,$_GET['id'],$admin_mode);
	if($user==null)
	{
		echo json_encode(array(	'id'=>(int)$_GET['id'],
								'use'=>1,
								'show'=>null,
								'name'=>null,
								'head'=>null,
								'ips'=>''
						));
		exit();			
	}
	if(!$user['use']&&!$jry_wb_login_user['compentence']['manageusers'])
	{
		echo json_encode(array(	'id'=>(int)$_GET['id'],
								'use'=>(int)$user['use'],
								'ips'=>''
						));
		exit();		
	}
	if((strtotime($user['lasttime'])-strtotime(urldecode($_GET['lasttime'])))<=0)
	{
		echo json_encode(array('id'=>-1,'use'=>1));
		exit();
	}
	if($_GET['action']=='new')
		$id=$user['id'];
	else
		$id=$_GET['id'];
	$data=array('id'=>(int)$id,
				'head'=>$user['head'],
				'head_special'=>$user['head_special'],
				'green_money'=>$user['green_money'],
				'enroldate'=>$user['enroldate'],
				'competencename'=>$user['competencename'],
				'color'=>$user['color'],						
				'name'=>$user['name'],
				'sex'=>$user['sex'],
				'tel'=>$user['tel'],
				'mail'=>$user['mail'],
				'language'=>$user['language'],
				'zhushi'=>$user['zhushi'],
				'lasttime'=>$user['lasttime'],
				'lasttime_sync'=>jry_wb_get_time(),
				'type'=>$user['type'],
				'use'=>$user['use'],							
				'oauth_qq'=>(($admin_mode||$user['oauth_show'])?$user['oauth_qq']->message:null),
				'oauth_mi'=>(($admin_mode||$user['oauth_show'])?$user['oauth_mi']->message:null),
				'oauth_github'=>(($admin_mode||$user['oauth_show'])?$user['oauth_github']->message:null),
				'oauth_gitee'=>(($admin_mode||$user['oauth_show'])?$user['oauth_gitee']->message:null),
				'login_addr'=>($user['ip_show']||($admin_mode))?$user['login_addr']:-1,
				'password'=>($admin_mode)?$user['password']:'',
				'extern'=>($admin_mode)?json_decode($user['extern']):''
				);
	echo json_encode($data);
?>